export const CREATE_DEPOSIT = 'CREATE_DEPOSIT';
export const CREATE_WITHDRAW = 'CREATE_WITHDRAW';
export const CREATE_TRANSFER = 'CREATE_TRANSFER';
export const FETCH_EXTRACT = 'FETCH_EXTRACT';
export const FETCH_USER = 'FETCH_USER';
